project_id = "jsiwkbowgmjzywxcywgd"

[functions.travel-assistant]
verify_jwt = false

[functions.booking-status-notification]
verify_jwt = false

[functions.payment-notification]
verify_jwt = false

[functions.admin-create-agency]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.internal-notification]
verify_jwt = false

[functions.fix-rls]
verify_jwt = false
