export const countryToIso: Record<string, string> = {
  Turkey: "tr",
  UAE: "ae",
  Malaysia: "my",
  Thailand: "th",
  Egypt: "eg",
  Indonesia: "id",
  India: "in",
  Jordan: "jo",
  Morocco: "ma",
  "Saudi Arabia": "sa",
  Oman: "om",
  Bahrain: "bh",
  Qatar: "qa",
  Kuwait: "kw",
  Georgia: "ge",
  Azerbaijan: "az",
  Maldives: "mv",
  "Sri Lanka": "lk",
  Kenya: "ke",
  Tanzania: "tz",
  "South Africa": "za",
  Tunisia: "tn",
  Lebanon: "lb",
  Iraq: "iq",
  Iran: "ir",
  Pakistan: "pk",
  Bangladesh: "bd",
  Nepal: "np",
  China: "cn",
  Japan: "jp",
  "South Korea": "kr",
  Philippines: "ph",
  Vietnam: "vn",
  Cambodia: "kh",
  Singapore: "sg",
  Australia: "au",
  "New Zealand": "nz",
  France: "fr",
  Italy: "it",
  Spain: "es",
  Germany: "de",
  UK: "gb",
  Greece: "gr",
  Portugal: "pt",
  Netherlands: "nl",
  Switzerland: "ch",
  Austria: "at",
  "Czech Republic": "cz",
  Poland: "pl",
  Hungary: "hu",
  Croatia: "hr",
  Sweden: "se",
  Norway: "no",
  Denmark: "dk",
  Finland: "fi",
  Belgium: "be",
  Ireland: "ie",
  USA: "us",
  Canada: "ca",
  Mexico: "mx",
  Brazil: "br",
  Argentina: "ar",
  Colombia: "co",
  Chile: "cl",
  Peru: "pe",
};

export function getCountryFlagUrl(country: string, width = 40): string | null {
  const iso = countryToIso[country];
  if (!iso) return null;
  return `https://flagcdn.com/w${width}/${iso}.png`;
}
